---
  - name: YUM update
    yum:
      name: '*'
      state: latest

  # - name: Install RPM packates
  #   yum:
  #     name: "{{ packages }}"

  - name: install needed rpm(s)
    yum:
      name: "{{ item }}"
      state: present
    with_items: "{{ packages }}"
    register: result
    until: result is succeeded

  - name: Enable SELinux
    selinux:
      policy: targeted
      state: enforcing
    register: selinux

  - name: Reboot Server after SELinux Change
    become: yes
    shell: sleep 2 && /sbin/shutdown -r now "System reboot"
    async: 1
    poll: 0
    when: selinux.reboot_required

  - name: Wait for Server to Come up
    local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}"  search_regex=OpenSSH delay=120
    when: selinux.reboot_required
